openapi: 3.1.3
info:
  title: Delete Appointment API
  description: Deletes an appointment for an insurance advisor by event ID.
  version: 1.0.0
servers:
  - url: https://callback-service-348511322333.europe-west3.run.app
    description: Production server
paths:
  /api/appointment/delete/{insurance_advisor_email}/{event_id}:
    delete:
      summary: Delete Appointment
      operationId: deleteAppointment
      parameters:
        - name: insurance_advisor_email
          in: path
          required: true
          schema:
            type: string
          description: Email address of the insurance advisor
          example: callback-service@rxry.onmicrosoft.com
        - name: event_id
          in: path
          required: true
          schema:
            type: string
          description: Event ID of the appointment to delete
          example: AAMkAGI2T...
      responses:
        '200':
          description: Appointment deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: deleted
        '404':
          description: Appointment not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: not found
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            oneOf:
                              - type: string
                              - type: integer
                        msg:
                          type: string
                        type:
                          type: string